x-runtipi:
  schema_version: 2
  overrides: []
services:
  wings:
    image: ghcr.io/pterodactyl/wings:v1.13.1
    networks:
      - wing0
    ports:
      - ${WINGS_SFTP_PORT-:2022}:2022
    environment:
      - TZ=${TZ}
      - WINGS_UID=988
      - WINGS_GID=988
      - WINGS_USERNAME=pterodactyl
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /etc/pterodactyl:/etc/pterodactyl
      - /var/lib/pterodactyl:/var/lib/pterodactyl
      - /var/log/pterodactyl:/var/log/pterodactyl
      - /tmp/pterodactyl:/tmp/pterodactyl
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /run/wings:/run/wings
      - /etc/letsencrypt:/etc/letsencrypt:ro
    x-runtipi:
      is_main: true
      internal_port: 8080

networks:
  wings0:
    name: wings0
    driver: bridge
    ipam:
      config:
        - subnet: "172.21.0.0/16"
    driver_opts:
      com.docker.network.bridge.name: wings0
