name: Renovate
on:
  workflow_dispatch:
    inputs:
      log_level:
        type: choice
        description: Log level
        default: INFO
        options:
          - DEBUG
          - INFO
          - WARN
          - ERROR
          - FATAL
  schedule:
    - cron: 0 2 * * *
  pull_request:
  merge_group:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Cache bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-renovate
          restore-keys: |
            ${{ runner.os }}-bun-renovate

      - name: Install Renovate
        run: bun install -g renovate re2

      - name: Echo repository
        run: echo ${{ github.repository }}

      - name: Run renovate
        run: LOG_LEVEL=${{ github.event.inputs.log_level || 'INFO' }} renovate --token ${{ steps.app-token.outputs.token }} ${{ github.repository }}
