name: Renovate
on:
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.2
        with:
          configurationFile: renovate-global.json
          docker-cmd-file: .github/scripts/renovate-entrypoint.sh
          docker-user: root
          token: ${{ secrets.GITHUB_TOKEN }}
          docker-volumes: |
            /home/runner/work/runtipi-appstore/runtipi-appstore:/home/runner/work/runtipi-appstore/runtipi-appstore
